version: "2"

services:

  eventstore1:
   image: krnissbrandt/eventstore-cluster-node-docker:3.9.3
   env_file:
     - common-variables.env
   environment:
     - EVENTSTORE_GOSSIP_SEED=172.16.0.12:2112,172.16.0.13:2112
     - EVENTSTORE_NODE_PRIORITY=3
     - EVENTSTORE_GOSSIP_TIMEOUT_MS=1000
     - EVENTSTORE_CLUSTER_GOSSIP_PORT=2112
     - EVENTSTORE_INT_IP=172.16.0.11
     - EVENTSTORE_EXT_HTTP_PORT=2113
     - EVENTSTORE_EXT_TCP_PORT=1113
     - EVENTSTORE_EXT_HTTP_PREFIXES=http://*:2113/
   ports:
     - 1113:1113
     - 2113:2113
   volumes:
     - "~/Data/eventstore3node/node1/db:/data/db"
     - "~/Data/eventstore3node/node1/logs:/data/logs"
   restart: always
   networks:
     clusternetwork:
       ipv4_address: 172.16.0.11
       
  eventstore2:
   image: krnissbrandt/eventstore-cluster-node-docker:3.9.3
   env_file:
     - common-variables.env
   environment:
     - EVENTSTORE_GOSSIP_SEED=172.16.0.11:2112,172.16.0.13:2112
     - EVENTSTORE_NODE_PRIORITY=2
     - EVENTSTORE_GOSSIP_TIMEOUT_MS=1000
     - EVENTSTORE_CLUSTER_GOSSIP_PORT=2112
     - EVENTSTORE_INT_IP=172.16.0.12
     - EVENTSTORE_EXT_HTTP_PORT=2123
     - EVENTSTORE_EXT_TCP_PORT=1123
     - EVENTSTORE_EXT_HTTP_PREFIXES=http://*:2123/
   ports:
     - 1123:1123
     - 2123:2123
   volumes:
     - "~/Data/eventstore3node/node2/db:/data/db"
     - "~/Data/eventstore3node/node2/logs:/data/logs"
   restart: always
   networks:
     clusternetwork:
       ipv4_address: 172.16.0.12
   
  eventstore3:
   image: krnissbrandt/eventstore-cluster-node-docker:3.9.3
   env_file:
     - common-variables.env
   environment:
     - EVENTSTORE_GOSSIP_SEED=172.16.0.11:2112,172.16.0.13:2112
     - EVENTSTORE_NODE_PRIORITY=1
     - EVENTSTORE_GOSSIP_TIMEOUT_MS=1000
     - EVENTSTORE_CLUSTER_GOSSIP_PORT=2112
     - EVENTSTORE_INT_IP=172.16.0.13
     - EVENTSTORE_EXT_HTTP_PORT=2133
     - EVENTSTORE_EXT_TCP_PORT=1133
     - EVENTSTORE_EXT_HTTP_PREFIXES=http://*:2133/
   ports:
     - 1133:1133
     - 2133:2133
   volumes:
     - "~/Data/eventstore3node/node3/db:/data/db"
     - "~/Data/eventstore3node/node3/logs:/data/logs"
   restart: always
   networks:
     clusternetwork:
       ipv4_address: 172.16.0.13

networks:
  clusternetwork:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.0/24
        gateway: 172.16.0.1    
